import { Product } from './product.model';

export const products: Product[] = [
  {
    id: 1,
    name: 'Laptop',
    description: 'Powerful laptop for gaming and productivity',
    price: 1299,
    images: [
      'https://example.com/laptop1.jpg',
      'https://example.com/laptop1_alt.jpg',
    ],
    brand: 'XYZ',
    tags: ['gaming', 'productivity', 'electronics'],
  },
  {
    id: 2,
    name: 'Smartphone',
    description: 'High-end smartphone with advanced features',
    price: 899,
    images: [
      'https://example.com/smartphone1.jpg',
      'https://example.com/smartphone1_alt.jpg',
    ],
    brand: 'ABC',
    tags: ['mobile', 'electronics'],
  },
  {
    id: 3,
    name: 'Headphones',
    description: 'Wireless headphones with noise cancellation',
    price: 199,
    images: [
      'https://example.com/headphones1.jpg',
      'https://example.com/headphones1_alt.jpg',
    ],
    brand: 'PQR',
    tags: ['audio', 'electronics'],
  },
  {
    id: 4,
    name: 'Camera',
    description: 'Professional DSLR camera for photography enthusiasts',
    price: 1499,
    images: [
      'https://example.com/camera1.jpg',
      'https://example.com/camera1_alt.jpg',
    ],
    brand: 'LMN',
    tags: ['photography', 'electronics'],
  },
  {
    id: 5,
    name: 'Television',
    description: 'Smart TV with 4K resolution',
    price: 1099,
    images: ['https://example.com/tv1.jpg', 'https://example.com/tv1_alt.jpg'],
    brand: 'XYZ',
    tags: ['entertainment', 'electronics'],
  },
  {
    id: 6,
    name: 'Tablet',
    description: 'Portable tablet for work and entertainment',
    price: 599,
    images: [
      'https://example.com/tablet1.jpg',
      'https://example.com/tablet1_alt.jpg',
    ],
    brand: 'ABC',
    tags: ['mobile', 'electronics'],
  },
  {
    id: 7,
    name: 'Smartwatch',
    description: 'Fitness tracker and smartwatch combo',
    price: 249,
    images: [
      'https://example.com/smartwatch1.jpg',
      'https://example.com/smartwatch1_alt.jpg',
    ],
    brand: 'PQR',
    tags: ['wearable', 'electronics'],
  },
  {
    id: 8,
    name: 'Drone',
    description: 'Compact drone for aerial photography',
    price: 699,
    images: [
      'https://example.com/drone1.jpg',
      'https://example.com/drone1_alt.jpg',
    ],
    brand: 'LMN',
    tags: ['photography', 'electronics'],
  },
  {
    id: 9,
    name: 'Printer',
    description: 'All-in-one printer for home and office',
    price: 299,
    images: [
      'https://example.com/printer1.jpg',
      'https://example.com/printer1_alt.jpg',
    ],
    brand: 'XYZ',
    tags: ['office', 'electronics'],
  },
  {
    id: 10,
    name: 'External Hard Drive',
    description: 'High-capacity external hard drive for data storage',
    price: 129,
    images: [
      'https://example.com/harddrive1.jpg',
      'https://example.com/harddrive1_alt.jpg',
    ],
    brand: 'ABC',
    tags: ['storage', 'electronics'],
  },
  {
    id: 11,
    name: 'Wireless Mouse',
    description: 'Ergonomic wireless mouse for comfortable use',
    price: 49,
    images: [
      'https://example.com/mouse1.jpg',
      'https://example.com/mouse1_alt.jpg',
    ],
    brand: 'PQR',
    tags: ['accessories', 'electronics'],
  },
  {
    id: 12,
    name: 'Gaming Console',
    description: 'Next-gen gaming console for immersive gaming experience',
    price: 399,
    images: [
      'https://example.com/console1.jpg',
      'https://example.com/console1_alt.jpg',
    ],
    brand: 'LMN',
    tags: ['gaming', 'electronics'],
  },
  {
    id: 13,
    name: 'Fitness Tracker',
    description: 'Track your fitness goals with this sleek fitness tracker',
    price: 79,
    images: [
      'https://example.com/fitnesstracker1.jpg',
      'https://example.com/fitnesstracker1_alt.jpg',
    ],
    brand: 'XYZ',
    tags: ['wearable', 'electronics'],
  },
  {
    id: 14,
    name: 'Bluetooth Speaker',
    description: 'Portable Bluetooth speaker for music lovers',
    price: 99,
    images: [
      'https://example.com/speaker1.jpg',
      'https://example.com/speaker1_alt.jpg',
    ],
    brand: 'ABC',
    tags: ['audio', 'electronics'],
  },
  {
    id: 15,
    name: 'Wireless Earbuds',
    description: 'True wireless earbuds for on-the-go music',
    price: 149,
    images: [
      'https://example.com/earbuds1.jpg',
      'https://example.com/earbuds1_alt.jpg',
    ],
    brand: 'PQR',
    tags: ['audio', 'electronics'],
  },
  {
    id: 16,
    name: 'Digital Camera',
    description: 'Compact digital camera for capturing memories',
    price: 299,
    images: [
      'https://example.com/digitalcamera1.jpg',
      'https://example.com/digitalcamera1_alt.jpg',
    ],
    brand: 'LMN',
    tags: ['photography', 'electronics'],
  },
  {
    id: 17,
    name: 'Smart Speaker',
    description: 'Voice-controlled smart speaker for home automation',
    price: 129,
    images: [
      'https://example.com/smartspeaker1.jpg',
      'https://example.com/smartspeaker1_alt.jpg',
    ],
    brand: 'XYZ',
    tags: ['smart home', 'electronics'],
  },
];
